import '../styles/globals.scss'
import type { Metadata } from 'next'

import LeftBar from '@/components/LeftBar'
import { useTypeSelector } from '@/store/hooks/useTypeSelector'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { isHide, loading, error } = useTypeSelector(
    (state) => state.hideBarReducer
  )
  return (
    <div className="wrapper">
      <LeftBar />
      <main className="main">
        <div className="main__container">
          <Header />
          {children}
        </div>
      </main>
      <div
        className="right-bar"
        style={{ flex: isHide ? '0 0 20%' : '0 0 0' }}
      ></div>
    </div>
  )
}
